import bcrypt from "bcrypt.js";

const data = {
  users: [
    {
      name: "Ravisankar Varadarajan",
      email: "ravisv73@gmail.com",
      password: bcrypt.hasSync("12345"),
      isAdmin: true,
    },
    {
      name: "Vishnuchakravarthy Varadarajan",
      email: "vishnu_chak@yahoo.com",
      password: bcrypt.hasSync("12345"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Paneer Butter Masala",
      slug: "paneer-butter-masala",
      category: "Side Dish",
      image: "/images/paneer_butter_masala.jpg",
      recipe_url: "http://localhost:8080/?p=11",
      price: 70,
      cuisine: "North-Indian",
      rating: 4.5,
      numReviews: 10,
      status: "Available",
      description: "A popular dish",
    },
    {
      name: "Thalapakattu Chicken Briyani",
      slug: "thalapakattu-briyani",
      category: "Main Dish",
      image: "/images/thalapakattu_briyani.jpg",
      recipe_url: "http://localhost:8080/?p=63",
      price: 120,
      cuisine: "Tamilnadu",
      rating: 4.75,
      numReviews: 30,
      status: "Available",
      description: "A popular dish",
    },
    {
      name: "A Vegetable fried rice",
      slug: "veg-fried-rice",
      category: "Main Dish",
      image: "/images/veg_fried_rice.jpg",
      recipe_url: "http://localhost:8080/?p=63",
      price: 90,
      cuisine: "Chinese",
      rating: 4.3,
      numReviews: 15,
      status: "Not Available",
      description: "A popular dish",
    },
    {
      name: "A Vegetable fried rice",
      slug: "veg-fried-rice-1",
      category: "Main Dish",
      image: "/images/veg_fried_rice.jpg",
      recipe_url: "http://localhost:8080/?p=63",
      price: 90,
      cuisine: "Chinese",
      rating: 4.3,
      numReviews: 15,
      status: "Available",
      description: "A popular dish",
    },
    {
      name: "Paneer Butter Masala",
      slug: "paneer-butter-masala-1",
      category: "Side Dish",
      image: "/images/paneer_butter_masala.jpg",
      recipe_url: "http://localhost:8080/?p=11",
      price: 70,
      cuisine: "North-Indian",
      rating: 4.5,
      numReviews: 10,
      status: "Not Available",
      description: "A popular dish",
    },
    {
      name: "Thalapakattu Mutton Briyani",
      slug: "thalapakattu-briyani-1",
      category: "Main Dish",
      image: "/images/thalapakattu_briyani.jpg",
      recipe_url: "http://localhost:8080/?p=77",
      price: 120,
      cuisine: "Tamilnadu",
      rating: 4.75,
      numReviews: 30,
      status: "Available",
      description: "A popular dish",
    },
    {
      name: "Paneer Butter Masala",
      slug: "paneer-butter-masala-2",
      category: "Side Dish",
      image: "/images/paneer_butter_masala.jpg",
      recipe_url: "http://localhost:8080/?p=11",
      price: 70,
      cuisine: "North-Indian",
      rating: 4.5,
      numReviews: 10,
      status: "Available",
      description: "A popular dish",
    },
    {
      name: "A Vegetable fried rice",
      slug: "veg-fried-rice-2",
      category: "Main Dish",
      image: "/images/veg_fried_rice.jpg",
      recipe_url: "http://localhost:8080/?p=63",
      price: 90,
      cuisine: "Chinese",
      rating: 4.3,
      numReviews: 15,
      status: "Available",
      description: "A popular dish",
    },
    {
      name: "Thalapakattu Briyani",
      slug: "thalapakattu-briyani-2",
      category: "Main Dish",
      image: "/images/thalapakattu_briyani.jpg",
      recipe_url: "http://localhost:8080/?p=63",
      price: 120,
      cuisine: "Tamilnadu",
      rating: 4.75,
      numReviews: 30,
      status: "Available",
      description: "A popular dish",
    },
  ],
};

export default data;
