
const productData = {
    products: [
        {
            name: 'Paneer Butter Masala',
            slug: 'paneer-butter-masala',
            masalaRecipeSlug: 'தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket',
            category: 'Side Dish',
            image: '/images/paneer_butter_masala.jpg',
            recipe_url: 'http://localhost:8080/?p=11',
            price: 70,
            cuisine: 'North-Indian',
            rating: 4.5,
            numReviews: 10,
            status: 'Available',
            description : 'A popular dish',
        },
        {
            name: 'Thalapakattu Chicken Briyani',
            slug: 'thalapakattu-briyani',
            masalaRecipeSlug: 'தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket',
            category: 'Main Dish',
            image: '/images/thalapakattu_briyani.jpg',
            recipe_url: 'http://localhost:8080/?p=63',
            price: 120,
            cuisine: 'Tamilnadu',
            rating: 4.75,
            numReviews: 30,
            status: 'Available',
            description : 'A popular dish',
        },
        {
            name: 'A Vegetable fried rice',
            slug: 'veg-fried-rice',
            masalaRecipeSlug: 'தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket',
            category: 'Main Dish',
            image: '/images/veg_fried_rice.jpg',
            recipe_url: 'http://localhost:8080/?p=63',
            price: 90,
            cuisine: 'Chinese',
            rating: 4.3,
            numReviews: 15,
            status: 'Not Available',
            description : 'A popular dish',
        },
        {
            name: 'A Vegetable fried rice',
            slug: 'veg-fried-rice-1',
            masalaRecipeSlug: 'தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket',
            category: 'Main Dish',
            image: '/images/veg_fried_rice.jpg',
            recipe_url: 'http://localhost:8080/?p=63',
            price: 90,
            cuisine: 'Chinese',
            rating: 4.3,
            numReviews: 15,
            status: 'Available',
            description : 'A popular dish',
        },
        {
            name: 'Paneer Butter Masala',
            slug: 'paneer-butter-masala-1',
            masalaRecipeSlug: 'தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket',
            category: 'Side Dish',
            image: '/images/paneer_butter_masala.jpg',
            recipe_url: 'http://localhost:8080/?p=11',
            price: 70,
            cuisine: 'North-Indian',
            rating: 4.5,
            numReviews: 10,
            status: 'Not Available',
            description : 'A popular dish',
        },
        {
            name: 'Thalapakattu Mutton Briyani',
            slug: 'thalapakattu-briyani-1',
            masalaRecipeSlug: 'தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket',
            category: 'Main Dish',
            image: '/images/thalapakattu_briyani.jpg',
            recipe_url: 'http://localhost:8080/?p=77',
            price: 120,
            cuisine: 'Tamilnadu',
            rating: 4.75,
            numReviews: 30,
            status: 'Available',
            description : 'A popular dish',
        },
        {
            name: 'Paneer Butter Masala',
            slug: 'paneer-butter-masala-2',
            masalaRecipeSlug: 'தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket',
            category: 'Side Dish',
            image: '/images/paneer_butter_masala.jpg',
            recipe_url: 'http://localhost:8080/?p=11',
            price: 70,
            cuisine: 'North-Indian',
            rating: 4.5,
            numReviews: 10,
            status: 'Available',
            description : 'A popular dish',
        },
        {
            name: 'A Vegetable fried rice',
            slug: 'veg-fried-rice-2',
            masalaRecipeSlug: 'தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket',
            category: 'Main Dish',
            image: '/images/veg_fried_rice.jpg',
            recipe_url: 'http://localhost:8080/?p=63',
            price: 90,
            cuisine: 'Chinese',
            rating: 4.3,
            numReviews: 15,
            status: 'Available',
            description : 'A popular dish',
        },
        {
            name: 'Thalapakattu Briyani',
            slug: 'thalapakattu-briyani-2',
            masalaRecipeSlug: 'தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket',
            category: 'Main Dish',
            image: '/images/thalapakattu_briyani.jpg',
            recipe_url: 'http://localhost:8080/?p=63',
            price: 120,
            cuisine: 'Tamilnadu',
            rating: 4.75,
            numReviews: 30,
            status: 'Available',
            description : 'A popular dish',
        },

    ],
};

export default productData;