const productData = {
  products: [
    {
      name: "Paneer Butter Masala",
      slug: "paneer-butter-masala",
      recipeSlug: "thalapakattu-briyani",
      masalaRecipeSlug: "தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket",
      category: "Side Dish",
      subCategory: "Paneer",
      image: "/images/paneer_butter_masala.jpg",
      recipe_url: "http://localhost:8080/?p=11",
      price: 70,
      cuisine: "North-Indian",
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
      status: "Available",
      description: "A popular dish",
      version: 1,
      versionStatus: "Current",
      release: "CooKQu-Rel-1_00",
      releaseStatus: "Current",
    },
    {
      name: "Thalapakattu Chicken Briyani",
      slug: "thalapakattu-briyani",
      recipeSlug: "thalapakattu-briyani",
      masalaRecipeSlug: "தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket",
      category: "Main Dish",
      subCategory: "Briyani",
      image: "/images/thalapakattu_briyani.jpg",
      recipe_url: "http://localhost:8080/?p=63",
      price: 120,
      cuisine: "Tamilnadu",
      rating: 4.75,
      numReviews: 30,
      countInStock: 10,
      status: "Available",
      description: "A popular dish",
      version: 1,
      versionStatus: "Current",
      release: "CooKQu-Rel-1_00",
      releaseStatus: "Current",
    },
    {
      name: "A Vegetable fried rice",
      slug: "veg-fried-rice",
      recipeSlug: "thalapakattu-briyani",
      masalaRecipeSlug: "தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket",
      category: "Breakfast",
      subCategory: "Rice",
      image: "/images/veg_fried_rice.jpg",
      recipe_url: "http://localhost:8080/?p=63",
      price: 90,
      cuisine: "Chinese",
      rating: 4.3,
      numReviews: 15,
      countInStock: 10,
      status: "Not Available",
      description: "A popular dish",
      version: 1,
      versionStatus: "Current",
      release: "CooKQu-Rel-1_00",
      releaseStatus: "Current",
    },
    {
      name: "A Vegetable fried rice",
      slug: "veg-fried-rice-1",
      recipeSlug: "thalapakattu-briyani",
      masalaRecipeSlug: "தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket",
      category: "Breakfast",
      subCategory: "Rice",
      image: "/images/veg_fried_rice.jpg",
      recipe_url: "http://localhost:8080/?p=63",
      price: 90,
      cuisine: "Chinese",
      rating: 4.3,
      numReviews: 15,
      countInStock: 1,
      status: "Available",
      description: "A popular dish",
      version: 1,
      versionStatus: "Current",
      release: "CooKQu-Rel-1_00",
      releaseStatus: "Current",
    },
    {
      name: "Paneer Butter Masala",
      slug: "paneer-butter-masala-1",
      recipeSlug: "thalapakattu-briyani",
      masalaRecipeSlug: "தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket",
      category: "Side Dish",
      subCategory: "Curry",
      image: "/images/paneer_butter_masala.jpg",
      recipe_url: "http://localhost:8080/?p=11",
      price: 70,
      cuisine: "North-Indian",
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
      status: "Not Available",
      description: "A popular dish",
      version: 1,
      versionStatus: "Current",
      release: "CooKQu-Rel-1_00",
      releaseStatus: "Current",
    },
    {
      name: "Thalapakattu Mutton Briyani",
      slug: "thalapakattu-briyani-1",
      recipeSlug: "thalapakattu-briyani",
      masalaRecipeSlug: "தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket",
      category: "Main Dish",
      subCategory: "Briyani",
      image: "/images/thalapakattu_briyani.jpg",
      recipe_url: "http://localhost:8080/?p=77",
      price: 120,
      cuisine: "Tamilnadu",
      rating: 4.75,
      numReviews: 30,
      countInStock: 10,
      status: "Available",
      description: "A popular dish",
      version: 1,
      versionStatus: "Current",
      release: "CooKQu-Rel-1_00",
      releaseStatus: "Current",
    },
    {
      name: "Paneer Butter Masala",
      slug: "paneer-butter-masala-2",
      recipeSlug: "thalapakattu-briyani",
      masalaRecipeSlug: "தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket",
      category: "Side Dish",
      subCategory: "Curry",
      image: "/images/paneer_butter_masala.jpg",
      recipe_url: "http://localhost:8080/?p=11",
      price: 70,
      cuisine: "North-Indian",
      rating: 4.5,
      numReviews: 10,
      countInStock: 8,
      status: "Available",
      description: "A popular dish",
      version: 1,
      versionStatus: "Current",
      release: "CooKQu-Rel-1_00",
      releaseStatus: "Current",
    },
    {
      name: "A Vegetable fried rice",
      slug: "veg-fried-rice-2",
      recipeSlug: "thalapakattu-briyani",
      masalaRecipeSlug: "தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket",
      category: "Breakfast",
      subCategory: "Rice",
      image: "/images/veg_fried_rice.jpg",
      recipe_url: "http://localhost:8080/?p=63",
      price: 90,
      cuisine: "Chinese",
      rating: 4.3,
      numReviews: 15,
      countInStock: 5,
      status: "Available",
      description: "A popular dish",
      version: 1,
      versionStatus: "Current",
      release: "CooKQu-Rel-1_00",
      releaseStatus: "Current",
    },
    {
      name: "Thalapakattu Briyani",
      slug: "thalapakattu-briyani-2",
      recipeSlug: "thalapakattu-briyani",
      masalaRecipeSlug: "தலபாக்கட்டு-பிரியாணி-மசாலா-பேக்-Pocket",
      category: "Main Dish",
      subCategory: "Briyani",
      image: "/images/thalapakattu_briyani.jpg",
      recipe_url: "http://localhost:8080/?p=63",
      price: 120,
      cuisine: "Tamilnadu",
      rating: 4.75,
      numReviews: 30,
      countInStock: 4,
      status: "Available",
      description: "A popular dish",
      version: 1,
      versionStatus: "Current",
      release: "CooKQu-Rel-1_00",
      releaseStatus: "Current",
    },
  ],
};

export default productData;
